package impl;

import java.sql.Connection;
import java.sql.SQLException;


import mapper.IMapper;
import domain.Dish;
import repo.*;
import uow.IUnitOfWork;

public class DishRepository extends RepositoryBase<Dish> implements IDishRepository {

	
	public DishRepository(Connection connection, IMapper<Dish> mapper, IUnitOfWork uow) throws SQLException{
		super(connection, mapper, uow);
		
	}

	@Override
	protected String getUpdateQuerySql() {
		return "UPDATE dish SET (name,description,price) = (?,?,?) WHERE id=?";
	}
	
	@Override
	protected String getInsertQuerySql() {
		return "INSERT INTO dish(name,description,price) VALUES (?,?,?)" ;
	}

	@Override
	protected String getTableName() {
		return "dish";
	}

	@Override
	protected String createTableStatementSql() {
		return "CREATE TABLE dish("
				+ "id bigint GENERATED BY DEFAULT AS IDENTITY,"
				+ "name varchar(30),"
				+ "description varchar(200)"
				+ "price float"
				+ ")";
	}

	@Override
	protected void setUpdate(Dish dish) throws SQLException {
		update.setString(1, dish.getName());
		update.setString(2, dish.getDescription());
		update.setFloat(3, dish.getPrice());
	}

	@Override
	protected void setInsert(Dish dish) throws SQLException {
		insert.setString(1, dish.getName());
		insert.setString(2, dish.getDescription());
		insert.setFloat(3, dish.getPrice());
	}



	
}
